
name: Issue Cycle Time Tracker

on:
  issues:
    types:
      - labeled
      - closed

jobs:
  track-cycle-time:
    runs-on: ubuntu-latest
    steps:
      - name: Set Start Date when moved to In Progress
        if: "github.event.action == 'labeled' && github.event.label.name.toLowerCase() == 'in progress'"
        uses: actions/github-script@v7
        with:
          script: |
            const startDate = new Date().toISOString().split('T')[0];
            await github.rest.issues.createComment({
              ...context.issue,
              body: `Start Date: ${startDate}`
            });

      - name: Set End Date and Calculate Cycle Time when Closed
        if: github.event.action == 'closed'
        uses: actions/github-script@v7
        with:
          script: |
            const endDate = new Date().toISOString().split('T')[0];

            const comments = await github.rest.issues.listComments({
              ...context.issue
            });

            let startDate = null;
            for (const comment of comments.data) {
              const match = comment.body.match(/Start Date: (\d{4}-\d{2}-\d{2})/i);
              if (match) {
                startDate = match[1];
                break;
              }
            }

            let cycleTimeMsg = '';
            if (startDate) {
              const start = new Date(startDate);
              const end = new Date(endDate);
              const diffTime = Math.abs(end - start);
              const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
              cycleTimeMsg = `Cycle Time: ${diffDays} day(s)`;
            } else {
              cycleTimeMsg = 'Cycle Time: Start Date not found.';
            }

            await github.rest.issues.createComment({
              ...context.issue,
              body: `End Date: ${endDate}\n${cycleTimeMsg}`
            });
