name: Issue Cycle Time Tracker

permissions:
  issues: write

on:
  issues:
    types:
      - labeled
      - closed

jobs:
  track-cycle-time:
    runs-on: ubuntu-latest
    steps:
      
      - name: Set Start Date when moved to In Progress
        if: github.event.action == 'labeled'
        uses: actions/github-script@v7
        with:
          script: |
            const label = github.event.label?.name?.toLowerCase();
            if (label === 'in progress') {
              const startDate = new Date().toISOString().split('T')[0];
              const { owner, repo } = context.repo;
              const issue_number = context.payload.issue.number;
      
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number,
                body: `Start Date: ${startDate}`
              });
            }

      - name: Set End Date and Calculate Cycle Time when Closed
        if: github.event.action == 'closed'
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const issue_number = context.payload.issue.number;
            const endDate = new Date().toISOString().split('T')[0];

            const comments = await github.rest.issues.listComments({
              owner,
              repo,
              issue_number
            });

            let startDate = null;
            for (const comment of comments.data) {
              const match = comment.body.match(/Start Date: (\d{4}-\d{2}-\d{2})/i);
              if (match) {
                startDate = match[1];
                break;
              }
            }

            let cycleTimeMsg = '';
            if (startDate) {
              const start = new Date(startDate);
              const end = new Date(endDate);
              const diffTime = Math.abs(end - start);
              const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
              cycleTimeMsg = `Cycle Time: ${diffDays} day(s)`;
            } else {
              cycleTimeMsg = 'Cycle Time: Start Date not found.';
            }

            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body: `End Date: ${endDate}\n${cycleTimeMsg}`
            });
